"""Light hyperparameter tuning with a single time-based validation block.

python -m carbon_forecast.models.tune

Validation = the `validation_months` of origins immediately before the Phase 4
test period. Training rows are purged so that no training target falls at or
after the validation start. The test period is never loaded. Writes
config/lgbm_params.yaml and reports/tuning.md.
"""

import argparse
import logging
import random
import time
from datetime import datetime

import pandas as pd
import yaml

from carbon_forecast.config import REPORTS_DIR, load_settings, resolve
from carbon_forecast.dataset import TARGET, feature_columns, load_training_set, time_split
from carbon_forecast.db import connect
from carbon_forecast.evaluate import score_table, skill
from carbon_forecast.models.baselines import BASELINE_SOURCES, predict_baselines
from carbon_forecast.models.lgbm import PARAMS_PATH, LGBMForecaster, variant_spec
from carbon_forecast.reporting import df_to_markdown

log = logging.getLogger(__name__)

SEARCH_SPACE = {
    "objective": ["regression", "regression_l1"],
    "learning_rate": [0.03, 0.05, 0.1],
    "num_leaves": [31, 63, 127, 255],
    "min_data_in_leaf": [50, 200, 1000],
    "feature_fraction": [0.6, 0.8, 1.0],
    "bagging_fraction": [0.7, 1.0],
    "lambda_l2": [0.0, 1.0, 10.0],
}


def sample_configs(n: int, seed: int) -> list[dict]:
    rng = random.Random(seed)
    configs: list[dict] = []
    while len(configs) < n:
        cfg = {k: rng.choice(v) for k, v in SEARCH_SPACE.items()}
        cfg["bagging_freq"] = 1 if cfg["bagging_fraction"] < 1 else 0
        if cfg not in configs:
            configs.append(cfg)
    return configs


def month_offset(d: datetime, months: int) -> datetime:
    m = d.month - 1 + months
    return d.replace(year=d.year + m // 12, month=m % 12 + 1)


def main(argv: list[str] | None = None) -> None:
    settings = load_settings()
    p = argparse.ArgumentParser(prog="python -m carbon_forecast.models.tune")
    p.add_argument("--db", default=settings["db_path"])
    p.add_argument("--n-search", type=int, default=settings["model"]["n_search"])
    args = p.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")

    m = settings["model"]
    test_start = datetime.combine(settings["evaluation"]["test_start"], datetime.min.time())
    val_start = month_offset(test_start, -settings["evaluation"]["validation_months"])
    with connect(resolve(args.db)) as con:
        df = load_training_set(con, end=test_start)  # the test period is never loaded
    log.info("loaded %d labelled rows with origin < %s", len(df), test_start)

    configs = sample_configs(args.n_search, m["seed"])
    tuned: dict[str, dict] = {}
    trials: list[dict] = []
    tuned_variants = [v for v, c in m["variants"].items() if "params_from" not in c]
    for variant in tuned_variants:
        cfg = m["variants"][variant]
        start = datetime.combine(cfg["train_start"], datetime.min.time())
        train, valid = time_split(df, val_start, train_start=start)
        feats = feature_columns(df, cfg["prefixes"], allow_leaky=cfg.get("leaky", False))
        log.info(
            "%s: %d train rows, %d validation rows, %d features",
            variant,
            len(train),
            len(valid),
            len(feats),
        )
        best = None
        for i, params in enumerate(configs, 1):
            t0 = time.time()
            model = LGBMForecaster(feats, params, m["max_boost_rounds"], seed=m["seed"])
            model.fit(train, valid, early_stopping_rounds=m["early_stopping_rounds"])
            val_mae = float((model.predict(valid) - valid[TARGET]).abs().mean())
            trials.append(
                {
                    "variant": variant,
                    "trial": i,
                    **params,
                    "best_iteration": model.best_iteration,
                    "val_mae": val_mae,
                    "seconds": round(time.time() - t0, 1),
                }
            )
            log.info(
                "  [%d/%d] val MAE %.3f at %d rounds (%.0fs)",
                i,
                len(configs),
                val_mae,
                model.best_iteration,
                time.time() - t0,
            )
            if best is None or val_mae < best[0]:
                best = (val_mae, params, model.best_iteration)
        tuned[variant] = {
            "params": best[1],
            "num_boost_round": int(best[2]),
            "validation_mae": round(best[0], 4),
        }

    header = (
        "# Generated by `python -m carbon_forecast.models.tune`; do not edit by hand.\n"
        f"# Validation origins {val_start:%Y-%m-%d} to {test_start:%Y-%m-%d} (exclusive); "
        "training targets purged before the validation start.\n"
    )
    PARAMS_PATH.write_text(header + yaml.safe_dump(tuned, sort_keys=False))

    # Validation comparison: every variant refit on its training split with the
    # chosen params, all scored on the same validation rows as the baselines.
    preds = predict_baselines(df)
    table_df = pd.concat([df[["origin_time_utc", "target_time_utc", TARGET]], preds], axis=1)
    table_df = table_df[table_df["origin_time_utc"] >= val_start].copy()
    for variant in m["variants"]:
        spec = variant_spec(variant, settings, tuned)
        start = datetime.combine(spec["train_start"], datetime.min.time())
        train, valid = time_split(df, val_start, train_start=start)
        feats = feature_columns(df, spec["prefixes"], allow_leaky=spec["leaky"])
        model = LGBMForecaster(
            feats,
            spec["params"],
            spec["num_boost_round"],
            seed=m["seed"],
            allow_leaky=spec["leaky"],
        ).fit(train)
        table_df.loc[valid.index, variant] = model.predict(valid)
    pred_cols = [*BASELINE_SOURCES, *m["variants"]]
    scores = score_table(table_df, TARGET, pred_cols)
    scores["skill_vs_seasonal_naive_day"] = [
        skill(v, scores.loc["seasonal_naive_day", "mae"]) for v in scores["mae"]
    ]
    write_report(pd.DataFrame(trials), scores, tuned, val_start, test_start)


def write_report(trials, scores, tuned, val_start, test_start) -> None:
    lines = [
        "# Hyperparameter tuning (validation only)",
        "",
        f"Validation origins: {val_start:%Y-%m-%d} to {test_start:%Y-%m-%d} (exclusive). "
        "Training rows are purged so no training target falls at or after the validation start. "
        "The Phase 4 test period is never loaded. Early stopping uses this same validation "
        "block, so these scores are mildly optimistic; the backtest in `reports/results.md` is "
        "the real out-of-sample evaluation.",
        "",
        "## Validation scores (all models on the same rows)",
        "",
        "`neso_stored_forecast` is a short-lead nowcast, not a 24-48h forecast; it is shown "
        "for reference and is not a like-for-like comparison. `oracle_weather` uses observed "
        "weather at the target time and is a leaky upper bound.",
        "",
        df_to_markdown(scores.reset_index(names="model"), ".3f"),
        "",
        "## Chosen parameters",
        "",
    ]
    for variant, t in tuned.items():
        lines += [
            f"**{variant}** (validation MAE {t['validation_mae']:.3f}, "
            f"{t['num_boost_round']} rounds): `{t['params']}`",
            "",
        ]
    lines += [
        "## All trials",
        "",
        df_to_markdown(trials.sort_values(["variant", "val_mae"]), ".3f"),
    ]
    out = REPORTS_DIR / "tuning.md"
    out.write_text("\n".join(lines) + "\n")
    print("\n".join(lines[: 12 + len(scores)]))
    print(f"written to {out} and {PARAMS_PATH}")


if __name__ == "__main__":
    main()
